//! CAS torrent 生成与解析
//!
//! 移植自 OpenList `pkg/torrent`，用于天翼云 CAS 秒传。
//! torrent 根字典含 `x-cas` 扩展：cloud/file_md5/slice_md5/slice_size/slice_md5s。

use crate::error::{Error, Result};

/// CAS 扩展根键
pub const CAS_EXTENSION_KEY: &str = "x-cas";
/// CAS 分片大小 key
pub const CAS_SLICE_SIZE_KEY: &str = "slice_size";
/// CAS 分片 MD5 列表 key
pub const CAS_SLICE_MD5S_KEY: &str = "slice_md5s";
/// CAS 最终分片 MD5 key
pub const CAS_SLICE_MD5_KEY: &str = "slice_md5";
/// CAS 整文件 MD5 key
pub const CAS_FILE_MD5_KEY: &str = "file_md5";
/// CAS 云盘类型 key
pub const CAS_CLOUD_KEY: &str = "cloud";

/// CAS 秒传所需信息
#[derive(Debug, Clone, Default)]
pub struct CasInfo {
    pub file_md5: String,
    pub slice_md5: String,
    pub slice_md5s: Vec<String>,
    pub slice_size: i64,
    pub cloud: String,
}

impl CasInfo {
    pub fn has_cas_info(&self) -> bool {
        !self.file_md5.is_empty() && !self.slice_md5.is_empty()
    }
}

/// 生成包含 CAS 扩展的 torrent 字节
///
/// - `file_md5`: 整文件 MD5（大写 hex）
/// - `slice_md5s`: 每个分片的 MD5（大写 hex）
/// - `slice_size`: 分片大小
/// - `piece_hashes`: 每个分片的 SHA-1（20 字节拼接）
pub fn generate_torrent(
    file_name: &str,
    file_size: i64,
    file_md5: &str,
    slice_md5s: &[String],
    slice_size: i64,
    piece_hashes: &[u8],
) -> Result<Vec<u8>> {
    let slice_md5 = if slice_md5s.len() > 1 {
        crate::crypto::md5_of_joined(&slice_md5s.iter().map(|s| s.as_str()).collect::<Vec<_>>())
    } else {
        file_md5.to_string()
    };

    let mut root = Vec::new();
    root.extend_from_slice(b"d");
    // comment (7 chars)
    root.extend_from_slice(b"7:comment");
    root.extend_from_slice(&bencode_str(b"Generated by TianyiCloud-Rust with CAS extension")?);
    // created by (10 chars)
    root.extend_from_slice(b"10:created by");
    root.extend_from_slice(&bencode_str(b"TianyiCloud-Rust")?);
    // creation date (13 chars)
    let now = crate::crypto::timestamp_ms() / 1000;
    root.extend_from_slice(b"13:creation date");
    root.extend_from_slice(&format!("i{}e", now).as_bytes().to_vec());

    // info 字典
    let mut info = Vec::new();
    info.extend_from_slice(b"d");
    info.extend_from_slice(b"12:piece length");
    info.extend_from_slice(&format!("i{}e", slice_size).as_bytes().to_vec());
    info.extend_from_slice(b"6:pieces");
    info.extend_from_slice(&bencode_bytes(piece_hashes)?);
    info.extend_from_slice(b"4:name");
    info.extend_from_slice(&bencode_str(file_name.as_bytes())?);
    info.extend_from_slice(b"6:length");
    info.extend_from_slice(&format!("i{}e", file_size).as_bytes().to_vec());
    info.extend_from_slice(b"6:md5sum");
    info.extend_from_slice(&bencode_str(file_md5.as_bytes())?);
    info.push(b'e');

    root.extend_from_slice(b"4:info");
    root.extend_from_slice(&info);

    // x-cas 扩展
    let mut cas = Vec::new();
    cas.extend_from_slice(b"d");
    cas.extend_from_slice(b"5:cloud");
    cas.extend_from_slice(&bencode_str(b"189")?);
    cas.extend_from_slice(b"8:file_md5");
    cas.extend_from_slice(&bencode_str(file_md5.as_bytes())?);
    cas.extend_from_slice(b"9:slice_md5");
    cas.extend_from_slice(&bencode_str(slice_md5.as_bytes())?);
    cas.extend_from_slice(b"10:slice_size");
    cas.extend_from_slice(&format!("i{}e", slice_size).as_bytes().to_vec());
    if !slice_md5s.is_empty() {
        cas.extend_from_slice(b"10:slice_md5s");
        cas.push(b'l');
        for md5 in slice_md5s {
            cas.extend_from_slice(&bencode_str(md5.as_bytes())?);
        }
        cas.push(b'e');
    }
    cas.push(b'e');

    root.extend_from_slice(b"5:x-cas");
    root.extend_from_slice(&cas);

    root.push(b'e');
    Ok(root)
}

/// 计算 torrent 的 info_hash（SHA-1，hex）
pub fn info_hash(data: &[u8]) -> String {
    use sha1::Digest;
    let h = sha1::Sha1::digest(data);
    hex::encode(h)
}

/// 从 torrent 解析 CAS 信息
pub fn parse_cas_info(data: &[u8]) -> Result<Option<CasInfo>> {
    let root = bencode_decode(data)?;
    let dict = root.as_dict()?;
    let cas_val = dict
        .iter()
        .find(|(k, _)| k.as_slice() == CAS_EXTENSION_KEY.as_bytes())
        .map(|(_, v)| v)
        .ok_or_else(|| Error::Other("no x-cas".into()))?;
    let cas_dict = cas_val.as_dict()?;
    let mut info = CasInfo::default();
    info.cloud = cas_dict
        .iter()
        .find(|(k, _)| k.as_slice() == CAS_CLOUD_KEY.as_bytes())
        .and_then(|(_, v)| v.as_str())
        .unwrap_or("")
        .to_string();
    info.file_md5 = cas_dict
        .iter()
        .find(|(k, _)| k.as_slice() == CAS_FILE_MD5_KEY.as_bytes())
        .and_then(|(_, v)| v.as_str())
        .unwrap_or("")
        .to_string();
    info.slice_md5 = cas_dict
        .iter()
        .find(|(k, _)| k.as_slice() == CAS_SLICE_MD5_KEY.as_bytes())
        .and_then(|(_, v)| v.as_str())
        .unwrap_or("")
        .to_string();
    info.slice_size = cas_dict
        .iter()
        .find(|(k, _)| k.as_slice() == CAS_SLICE_SIZE_KEY.as_bytes())
        .and_then(|(_, v)| v.as_int())
        .unwrap_or(0);
    if let Some((_, list)) = cas_dict
        .iter()
        .find(|(k, _)| k.as_slice() == CAS_SLICE_MD5S_KEY.as_bytes())
    {
        if let Some(items) = list.as_list() {
            for item in items {
                if let Some(s) = item.as_str() {
                    info.slice_md5s.push(s.to_string());
                }
            }
        }
    }
    if info.has_cas_info() {
        Ok(Some(info))
    } else {
        Ok(None)
    }
}

// ---------------------------------------------------------------------------
// 极简 bencode 实现
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
enum BVal {
    Int(i64),
    Bytes(Vec<u8>),
    List(Vec<BVal>),
    Dict(Vec<(Vec<u8>, BVal)>),
}

impl BVal {
    fn as_dict(&self) -> Result<&Vec<(Vec<u8>, BVal)>> {
        match self {
            BVal::Dict(d) => Ok(d),
            _ => Err(Error::Other("not a dict".into())),
        }
    }
    fn as_str(&self) -> Option<&str> {
        match self {
            BVal::Bytes(b) => std::str::from_utf8(b).ok(),
            _ => None,
        }
    }
    fn as_int(&self) -> Option<i64> {
        match self {
            BVal::Int(i) => Some(*i),
            _ => None,
        }
    }
    fn as_list(&self) -> Option<&Vec<BVal>> {
        match self {
            BVal::List(l) => Some(l),
            _ => None,
        }
    }
}

fn bencode_str(b: &[u8]) -> Result<Vec<u8>> {
    let mut out = Vec::new();
    out.extend_from_slice(format!("{}:", b.len()).as_bytes());
    out.extend_from_slice(b);
    Ok(out)
}

fn bencode_bytes(b: &[u8]) -> Result<Vec<u8>> {
    bencode_str(b)
}

/// 解析 bencode（仅支持 root 为 dict 的情况）
fn bencode_decode(data: &[u8]) -> Result<BVal> {
    let (val, rest) = parse_val(data)?;
    if !rest.is_empty() {
        return Err(Error::Other("trailing bytes".into()));
    }
    Ok(val)
}

fn parse_val(data: &[u8]) -> Result<(BVal, &[u8])> {
    if data.is_empty() {
        return Err(Error::Other("empty bencode".into()));
    }
    match data[0] {
        b'i' => {
            let end = data.iter().position(|&b| b == b'e').ok_or_else(|| Error::Other("no int end".into()))?;
            let s = std::str::from_utf8(&data[1..end]).map_err(|_| Error::Other("bad int".into()))?;
            let n = s.parse::<i64>().map_err(|_| Error::Other("bad int value".into()))?;
            Ok((BVal::Int(n), &data[end + 1..]))
        }
        b'l' => {
            let mut rest = &data[1..];
            let mut items = Vec::new();
            loop {
                if rest.is_empty() {
                    return Err(Error::Other("unterminated list".into()));
                }
                if rest[0] == b'e' {
                    return Ok((BVal::List(items), &rest[1..]));
                }
                let (item, r) = parse_val(rest)?;
                items.push(item);
                rest = r;
            }
        }
        b'd' => {
            let mut rest = &data[1..];
            let mut items = Vec::new();
            loop {
                if rest.is_empty() {
                    return Err(Error::Other("unterminated dict".into()));
                }
                if rest[0] == b'e' {
                    return Ok((BVal::Dict(items), &rest[1..]));
                }
                let (k, r) = parse_bytes(rest)?;
                let (v, r2) = parse_val(r)?;
                let k_bytes = match k {
                    BVal::Bytes(b) => b,
                    _ => return Err(Error::Other("dict key not bytes".into())),
                };
                items.push((k_bytes, v));
                rest = r2;
            }
        }
        _ => parse_bytes(data),
    }
}

fn parse_bytes(data: &[u8]) -> Result<(BVal, &[u8])> {
    let colon = data
        .iter()
        .position(|&b| b == b':')
        .ok_or_else(|| Error::Other("no colon".into()))?;
    let len_str = std::str::from_utf8(&data[..colon]).map_err(|_| Error::Other("bad len".into()))?;
    let len = len_str
        .parse::<usize>()
        .map_err(|_| Error::Other("bad len value".into()))?;
    if data.len() < colon + 1 + len {
        return Err(Error::Other("short string".into()));
    }
    let bytes = &data[colon + 1..colon + 1 + len];
    Ok((BVal::Bytes(bytes.to_vec()), &data[colon + 1 + len..]))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_and_parse_cas() {
        let slice_md5s = vec!["A1B2C3D4E5F60718293A4B5C6D7E8F90".to_string()];
        let torrent = generate_torrent(
            "test.txt",
            100,
            "0123456789ABCDEF0123456789ABCDEF",
            &slice_md5s,
            1024 * 1024,
            &[0u8; 20],
        )
        .unwrap();
        assert!(!torrent.is_empty());

        let cas = parse_cas_info(&torrent).unwrap().unwrap();
        assert_eq!(cas.cloud, "189");
        assert_eq!(cas.file_md5, "0123456789ABCDEF0123456789ABCDEF");
        assert_eq!(cas.slice_size, 1024 * 1024);
        assert_eq!(cas.slice_md5s.len(), 1);
        assert!(cas.has_cas_info());
    }
}
